int call_pwd(char *,int);
int call_echo(char **);
int call_cd(char *,char *);
int call_ls_a(char **,int,char *,int);
int call_lsl_a(char **,int,char *,int);
int call_lsdir(char **,int,char *,int);
int call_ground(char **,int);
int call_fg(char **,int);
int call_bg(char **,int);
int call_pinfo(char **);
int call_setenv(char **,int);
int call_unsetenv(char **,int);
int call_red(char **,int,int,int);